### ISSUE TITLE
My PhotosynQ is not measuring Chlorophll Fluorescence

### ISSUE THREAD

**Issue by alejandro2085** [Photosynq/PhotosynQ-Documentation#4]
Hello, 

I have 3 PhotosynQ and they are not measuring Phi2, PhiNPQ, PhiNO, NPQt, qL, LEF. When I turn on them or restarted they measure those parameters but just once, if I want to do another measurement again I have to restart the machines. I try seeing if the results were hidden, as it suggested in the forum, or download the Excel file with the results but still not getting it. You can see the result in my project LEC 244. I am using the protocol Leaf Photosynthesis MultispecQ V2.0. 

Many thanks in advance.

**Comment by SeBassTian23** [comment]
Hi,

I'm looking at your data right now and see if I can find the issue. It seems like it is a calculation problem. Please use the **Photosynthesis RIDES** protocol, it is the more advanced measurement protocol!

For future references, if you have questions like this, please post them on the [PhotosynQ Forum](https://photosynq.org/forums), since this is only for suggestions, comments and issues with the documentation, not technical issues or support with Instruments.
